# TDDE16 Project fake news classification perfomrance between BERT and Naive Bayes and Logic regression
In this project I will compare data of fake news from the dataset kaggle provides https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset

I will train and compare the performance of different techinques, namely googles BERT technology and some techinques performed in the lab

## 1: Fake new classification with Logic regression

In [16]:
#!pip3 install pandas
#!pip3 install spacy
#!pip3 install numpy

Requirement already satisfied: pandas in ./env/lib/python3.11/site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in ./env/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./env/lib/python3.11/site-packages (from pandas) (2022.6)
Requirement already satisfied: numpy>=1.21.0 in ./env/lib/python3.11/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: spacy in ./env/lib/python3.11/site-packages (3.4.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.10 in ./env/lib/python3.11/site-packages (from spacy) (3.0.10)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./env/lib/python3.11/site-packages (from spacy) (1.0.3)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./env/lib/python3.11/site-packages (from spacy) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./env/lib/python3.11/site-packages (from spacy) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./env/lib/python3.11/site-packages (from spacy) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in ./env/lib/python3.11/site-packages (from spacy) (8.1.5)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in ./env/lib/python3.11/site-packages (from spacy) (0.10.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./env/lib/python3.11/site-packages (from spacy) (2.4.5)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./env/lib/python3.11/site-packages (from spacy) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in ./env/lib/python3.11/site-packages (from spacy) (0.7.0)
Requirement already satisfied: pathy>=0.3.5 in ./env/lib/python3.11/site-packages (from spacy) (0.10.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./env/lib/python3.11/site-packages (from spacy) (4.64.1)
Requirement already satisfied: numpy>=1.15.0 in ./env/lib/python3.11/site-packages (from spacy) (1.23.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./env/lib/python3.11/site-packages (from spacy) (2.28.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in ./env/lib/python3.11/site-packages (from spacy) (1.10.2)
Requirement already satisfied: jinja2 in ./env/lib/python3.11/site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in ./env/lib/python3.11/site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in ./env/lib/python3.11/site-packages (from spacy) (22.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./env/lib/python3.11/site-packages (from spacy) (3.3.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in ./env/lib/python3.11/site-packages (from pathy>=0.3.5->spacy) (6.2.0)
Requirement already satisfied: typing-extensions>=4.1.0 in ./env/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.4.0)
Requirement already satisfied: charset-normalizer<3,>=2 in ./env/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./env/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in ./env/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./env/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.0.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in ./env/lib/python3.11/site-packages (from typer<0.8.0,>=0.3.0->spacy) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./env/lib/python3.11/site-packages (from jinja2->spacy) (2.1.1)

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: numpy in ./env/lib/python3.11/site-packages (1.23.5)

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip

## Creating a Dataframe

In [17]:
# import the dataset as a pandas dataframe
import pandas as pd
import spacy

fake_df = pd.read_csv("Fake.csv")
true_df = pd.read_csv("True.csv")

Add a label if the news is fake or true

In [18]:
fake_df['Label'] = False
true_df['Label'] = True

In [24]:
fake_df.head(10)

,title,text,subject,date,Label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",False
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",False
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",False
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",False
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",False
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",False
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",False
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",False
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",False
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",False

In [23]:
true_df.head(10)

,title,text,subject,date,Label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",True
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",True
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",True
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",True
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",True
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017",True
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017",True
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017",True
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017",True
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017",True

Combine both of the dataframes to one and remove columns that does not provide any data

In [27]:
df = pd.concat([fake_df, true_df], axis = 0)
df = df.drop(['subject', 'date'], axis = 1)

In [28]:
df['Label'].value_counts()

False    23481
True     21417
Name: Label, dtype: int64

## Using naive bayes as a baseline

Now we will create a training and test set from the dataframe

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'],df['Label'], test_size = 0.3, random_state = 10)

Simmilar to the labs I will test the MultinomialNB with a count Vectorizer to show the score

In [32]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer

pipe = Pipeline(steps=[('countVec', CountVectorizer()), ('multNB', MultinomialNB())])

pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

       False       0.96      0.95      0.95      7037
        True       0.95      0.95      0.95      6433

    accuracy                           0.95     13470
   macro avg       0.95      0.95      0.95     13470
weighted avg       0.95      0.95      0.95     13470

Getting a baseline from dummytest

In [33]:
from sklearn.dummy import DummyClassifier
dummy_clf = DummyClassifier(strategy="stratified")
dummy_clf.fit(X_train,y_train)
dummy_prediction = dummy_clf.predict(X_train)

print(classification_report(y_train, dummy_prediction))

              precision    recall  f1-score   support

       False       0.52      0.51      0.52     16444
        True       0.47      0.48      0.48     14984

    accuracy                           0.50     31428
   macro avg       0.50      0.50      0.50     31428
weighted avg       0.50      0.50      0.50     31428

## Using BERT to evaluate performance